### ISSUE TITLE
how to map js file to html?

### ISSUE THREAD

**Issue by 94q** [naveen-kumawat/Flower#3]
I can't seem to get it to work, i've done everything besides mapping js to html. 

Not sure how to do it, i've searched on youtube but pointless

**Comment by naveen-kumawat** [comment]
To get started, first install SCSS globally using npm:

`npm install -g sass`
Next, compile your SCSS file to CSS and watch for changes by running:

`sass --watch style.scss:style.css`

Make sure you're executing these commands in your project's root directory. Additionally, you'll want to run a live server to preview your changes. 

If you need further guidance, you can refer to the complete YouTube video by searching for "search4code" and subscribing to the channel using the link below:

YouTube Channel 👉 [ Search4Code](https://www.youtube.com/@search4code?sub_confirmation=1)
